### ISSUE TITLE
API HTTP verbs and document issues

### ISSUE THREAD

**Issue by YingLiu4203** [reactivesw/customer-info#5]
All update/delete operation should use the "POST", not "GET", HPTT verb. Need change in both code and doc.

The CustomerView model is missing.

When create a customer or a new address,  which field is nullable or no-null? 

The document should state that the returned addresses are in the order of creation.

**Comment by kaka89** [comment]
1, We are using `PUT` not `GET`, and  we will always use `PUT` for update, `delete` for delete.

2, The model is in the `README`, but now, I moved it to api doc.

3-4, Added these info in api doc
