### ISSUE TITLE
All single line comments should have a space after //

### ISSUE THREAD

**Issue by YingLiu4203** [reactivesw/customer-info#6]
As recommended by https://google.github.io/styleguide/javaguide.html#s4.8.6-comments, a single line comment should be in the form of 

```java
// a space between the leading "//" and text
```

For example, in `build.gradle`, there is a comment `//for docker build`  that doesn't follow the rule. 

Please find and fix all not-well-formatted comments.

**Comment by kaka89** [comment]
see [this pull request](https://github.com/reactivesw/customer-info/pull/7)
